name: CI

on: push

jobs:
  test:
    name: CI

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: NPM Install
        run: npm ci --ignore-scripts --prefer-offline
      - name: Test
        run: npm test
